services:
  chatbot-api:
    build:
        context: .
        dockerfile: docker/api/Dockerfile
    image: chatbot_api
    container_name: chatbot_api
    ports:
      - "127.0.0.1:9000:8000"
    env_file:
      - ./.env
    environment:
      - CHATBOT_API_LOG_LEVEL=INFO
      - DB__HOST=chatbot_postgres
      - AWS_ENDPOINT_URL_S3=http://chatbot-localstack:4566
    volumes:
      - .:/app
    depends_on:
      - chatbot-postgres
      - chatbot-localstack

  chatbot-postgres:
    image: postgres:15-alpine
    container_name: chatbot_postgres
    environment:
      - POSTGRES_USER=${DB__USER}
      - POSTGRES_PASSWORD=${DB__PASSWORD}
      - POSTGRES_DB=${DB__NAME}
    ports:
      - "127.0.0.1:5433:5432"

  chatbot-localstack:
    image: localstack/localstack
    container_name: chatbot_localstack
    environment:
      - DEBUG=0
      - SERVICES=s3
      - X_DEFAULT_REGION=us-east-1
    ports:
      - "127.0.0.1:4567:4566"
    volumes:
      - "./docker/localstack/init-resources.sh:/etc/localstack/init/ready.d/init-resources.sh"
      - "/var/run/docker.sock:/var/run/docker.sock"
    env_file:
      - ./.env