"""remove unique constraint from session_agent_messages

Revision ID: 36b555d3f40e
Revises: e67a5d952e34
Create Date: 2025-10-16 07:32:54.185899

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '36b555d3f40e'
down_revision: Union[str, Sequence[str], None] = 'e67a5d952e34'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_session_agent_message_index'), 'session_agent_messages', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq_session_agent_message_index'), 'session_agent_messages', ['agent_id', 'session_id', 'agent_message_index'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
