"""add tbl user_chat_requests

Revision ID: d08799c65f89
Revises: 36b555d3f40e
Create Date: 2025-10-17 06:00:55.617854

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "d08799c65f89"
down_revision: Union[str, Sequence[str], None] = "36b555d3f40e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_chat_requests",
        sa.Column("request_id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("session_id", sa.BigInteger(), nullable=False),
        sa.Column("request_start_time", sa.DateTime(timezone=True), nullable=False),
        sa.Column("request_end_time", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "request_processing_time", sa.DECIMAL(precision=10, scale=3), nullable=True
        ),
        sa.Column("request_user_query", sa.Text(), nullable=False),
        sa.Column("request_agent_response", sa.Text(), nullable=True),
        sa.Column("request_created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "request_updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column("response_status_code", sa.SmallInteger(), nullable=True),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["user_sessions.session_id"],
            name=op.f("user_chat_requests_session_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("request_id", name=op.f("user_chat_requests_pkey")),
        comment="Stores information about individual user requests within a session",
    )
    op.create_index(
        op.f("ix_user_chat_requests_request_end_time"),
        "user_chat_requests",
        ["request_end_time"],
        unique=False,
    )
    op.create_index(
        op.f("ix_user_chat_requests_request_start_time"),
        "user_chat_requests",
        ["request_start_time"],
        unique=False,
    )
    op.create_index(
        op.f("ix_user_chat_requests_session_id"),
        "user_chat_requests",
        ["session_id"],
        unique=False,
    )
    op.drop_index(op.f("ix_user_requests_request_end_time"), table_name="user_requests")
    op.drop_index(
        op.f("ix_user_requests_request_start_time"), table_name="user_requests"
    )
    op.drop_index(op.f("ix_user_requests_session_id"), table_name="user_requests")
    op.drop_table("user_requests")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_requests",
        sa.Column("request_id", sa.BIGINT(), autoincrement=True, nullable=False),
        sa.Column("session_id", sa.BIGINT(), autoincrement=False, nullable=False),
        sa.Column(
            "request_start_time",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "request_end_time",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "request_processing_time",
            sa.NUMERIC(precision=10, scale=3),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "request_created_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "request_updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "response_status_code", sa.SMALLINT(), autoincrement=False, nullable=True
        ),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["user_sessions.session_id"],
            name=op.f("user_requests_session_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("request_id", name=op.f("user_requests_pkey")),
        comment="Stores information about individual user requests within a session",
    )
    op.create_index(
        op.f("ix_user_requests_session_id"),
        "user_requests",
        ["session_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_user_requests_request_start_time"),
        "user_requests",
        ["request_start_time"],
        unique=False,
    )
    op.create_index(
        op.f("ix_user_requests_request_end_time"),
        "user_requests",
        ["request_end_time"],
        unique=False,
    )
    op.drop_index(
        op.f("ix_user_chat_requests_session_id"), table_name="user_chat_requests"
    )
    op.drop_index(
        op.f("ix_user_chat_requests_request_start_time"),
        table_name="user_chat_requests",
    )
    op.drop_index(
        op.f("ix_user_chat_requests_request_end_time"), table_name="user_chat_requests"
    )
    op.drop_table("user_chat_requests")
    # ### end Alembic commands ###
