"""add initial necessary tables

Revision ID: e67a5d952e34
Revises: 
Create Date: 2025-09-30 05:48:46.471384

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e67a5d952e34'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_sessions',
    sa.Column('session_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('session_uuid', sa.UUID(), nullable=False),
    sa.Column('user_uuid', sa.UUID(), nullable=False),
    sa.Column('session_type', sa.String(), nullable=False),
    sa.Column('session_created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('session_updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('session_id', name=op.f('user_sessions_pkey')),
    comment='Stores information about user sessions'
    )
    op.create_index(op.f('ix_user_sessions_session_uuid'), 'user_sessions', ['session_uuid'], unique=True)
    op.create_index(op.f('ix_user_sessions_user_uuid'), 'user_sessions', ['user_uuid'], unique=False)
    op.create_table('session_agents',
    sa.Column('agent_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.BigInteger(), nullable=False),
    sa.Column('agent_name', sa.String(length=255), server_default='default', nullable=False),
    sa.Column('agent_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('agent_created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('agent_updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['user_sessions.session_id'], name=op.f('session_agents_session_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('agent_id', name=op.f('session_agents_pkey')),
    comment='Stores information about agents associated with user sessions'
    )
    op.create_index(op.f('ix_session_agents_session_id'), 'session_agents', ['session_id'], unique=False)
    op.create_table('user_requests',
    sa.Column('request_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.BigInteger(), nullable=False),
    sa.Column('request_start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('request_end_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('request_processing_time', sa.DECIMAL(precision=10, scale=3), nullable=True),
    sa.Column('request_created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('request_updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('response_status_code', sa.SmallInteger(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['user_sessions.session_id'], name=op.f('user_requests_session_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('request_id', name=op.f('user_requests_pkey')),
    comment='Stores information about individual user requests within a session'
    )
    op.create_index(op.f('ix_user_requests_request_end_time'), 'user_requests', ['request_end_time'], unique=False)
    op.create_index(op.f('ix_user_requests_request_start_time'), 'user_requests', ['request_start_time'], unique=False)
    op.create_index(op.f('ix_user_requests_session_id'), 'user_requests', ['session_id'], unique=False)
    op.create_table('session_agent_messages',
    sa.Column('message_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('agent_id', sa.BigInteger(), nullable=False),
    sa.Column('session_id', sa.BigInteger(), nullable=False),
    sa.Column('agent_message_index', sa.BigInteger(), nullable=False, comment='Index of the message in the conversation history for this agent'),
    sa.Column('message_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('message_created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('message_updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['session_agents.agent_id'], name=op.f('session_agent_messages_agent_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['user_sessions.session_id'], name=op.f('session_agent_messages_session_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('message_id', name=op.f('session_agent_messages_pkey')),
    sa.UniqueConstraint('agent_id', 'session_id', 'agent_message_index', name='uq_session_agent_message_index'),
    comment='Stores messages exchanged between users and agents within a session'
    )
    op.create_index(op.f('ix_session_agent_messages_agent_id'), 'session_agent_messages', ['agent_id'], unique=False)
    op.create_index(op.f('ix_session_agent_messages_session_id'), 'session_agent_messages', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_session_agent_messages_session_id'), table_name='session_agent_messages')
    op.drop_index(op.f('ix_session_agent_messages_agent_id'), table_name='session_agent_messages')
    op.drop_table('session_agent_messages')
    op.drop_index(op.f('ix_user_requests_session_id'), table_name='user_requests')
    op.drop_index(op.f('ix_user_requests_request_start_time'), table_name='user_requests')
    op.drop_index(op.f('ix_user_requests_request_end_time'), table_name='user_requests')
    op.drop_table('user_requests')
    op.drop_index(op.f('ix_session_agents_session_id'), table_name='session_agents')
    op.drop_table('session_agents')
    op.drop_index(op.f('ix_user_sessions_user_uuid'), table_name='user_sessions')
    op.drop_index(op.f('ix_user_sessions_session_uuid'), table_name='user_sessions')
    op.drop_table('user_sessions')
    # ### end Alembic commands ###
